INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (1,'Billy', 'Conner');
INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (2,'John', 'Doe');
INSERT INTO AUTHOR (ID, FIRST_NAME, LAST_NAME) VALUES (3,'Bruce', 'Banner');

INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Spring Boot for the Non-Enthusiast', 1);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Nobody knows', 2);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('Using Angular 4 with Spring Boot', 1);
INSERT INTO BOOK (TITLE, AUTHOR_ID) VALUES ('How a fly ruined my date', 3);